version: '3.1'

services:
  web:
    container_name: '${NAME}-web'
    environment:
      - TZ=Europe/Moscow
    image: "abiosoft/caddy:latest"
    restart: always
    links:
      - app:php
    working_dir: /var/www/
    volumes:
      - ./../:/var/www:delegated
      - ./caddy/Caddyfile:/etc/Caddyfile
    ports:
      - ${WEB_PORT}:80

  app:
    container_name: '${NAME}-app'
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./php
    restart: always
    working_dir: /var/www/
    links:
      - db:mysql
    volumes:
      - ./../:/var/www:delegated

  db:
    container_name: '${NAME}-db'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - mysql:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

volumes:
  mysql:
